services:
  jh-de:
    build:
      context: .
      dockerfile: dockerfile.dev
    working_dir: /app
    command: sh -c "npm install --no-fund --no-audit && npm run dev -- --host --port 3000"
    environment:
      - NODE_ENV=development
      - ASTRO_TELEMETRY_DISABLED=1
      - SITE_URL=${JH_APP_URL_DEV:-https://jh.ixr.dev}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${JH_DEV_PORT:-6201}:3000"
    restart: unless-stopped
